=== R0ss/threefortythreetwo/a4/responses.dtd
<!-- a response will indicate when the student has not completed the survey yet -->
<!ELEMENT Responses (Student*)>
<!ELEMENT Student (Answer*)>
<!ELEMENT Answer (#PCDATA)>

<!ATTLIST Student ID ID #REQUIRED>

=== R0ss/threefortythreetwo/a4/responses.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Responses SYSTEM "responses.dtd">
<Responses>
  <Student>
		<ID>"g0cookie"</ID>
		<Answer>Vic</Answer>
		<Answer>3</Answer>
		<Answer>csc309; csc318</Answer>
		<Answer>recommender systems; human genome</Answer>
		<Answer>Mondays, 3pm: yes</Answer>
		<Answer>Mondays, 4pm: no</Answer>
		<Answer>Tuesday evenings (after 5pm): yes</Answer>
		<Answer>Fridays, 11am: yes</Answer>
	</Student>
	<Student>
		<ID>"g0ernie"</ID>
		<Answer>New</Answer>
		<Answer>3</Answer>
		<Answer>csc336/350</Answer>
		<Answer>human genome; location-aware apps</Answer>
		<Answer>Mondays, 3pm: yes</Answer>
		<Answer>Mondays, 4pm: yes</Answer>
		<Answer>Tuesday evenings (after 5pm): yes</Answer>
		<Answer>Fridays, 11am: yes</Answer>
	</Student>
	<Student>
		<ID>"g0bigbir"</ID>
		<Answer>Vic</Answer>
		<Answer>4</Answer>
		<Answer>csc318; csc343</Answer>
		<Answer>human genome; image processing</Answer>
		<Answer>Mondays, 3pm: no</Answer>
		<Answer>Mondays, 4pm: yes</Answer>
		<Answer>Tuesday evenings (after 5pm): yes</Answer>
		<Answer>Fridays, 11am: no</Answer>
	</Student>
	<Student>
		<ID>"g0dora"</ID>
		<Answer>Innis</Answer>
		<Answer>2</Answer>
		<Answer>took none of the courses</Answer>
		<Answer>image processing; encryption</Answer>
		<Answer>Mondays, 3pm: no</Answer>
		<Answer>Mondays, 4pm: no</Answer>
		<Answer>Tuesday evenings (after 5pm): yes</Answer>
		<Answer>Fridays, 11am: no</Answer>
	</Student>
	<Student>
		<ID>"g0diego"</ID>
		<Answer>Innis</Answer>
		<Answer>4</Answer>
		<Answer>csc318</Answer>
		<Answer>image processing; encryption</Answer>
		<Answer>Mondays, 3pm: no</Answer>
		<Answer>Mondays, 4pm: yes</Answer>
		<Answer>Tuesday evenings (after 5pm): yes</Answer>
		<Answer>Fridays, 11am: yes</Answer>
	</Student>
	<Student>
		<ID>"g0max"</ID>
		<Answer>UC</Answer>
		<Answer>3</Answer>
		<Answer>csc309; csc343</Answer>
		<Answer>human genome; encryption</Answer>
		<Answer>Mondays, 3pm: yes</Answer>
		<Answer>Mondays, 4pm: yes</Answer>
		<Answer>Tuesday evenings (after 5pm): yes</Answer>
		<Answer>Fridays, 11am: no</Answer>
	</Student>
	<Student>
		<ID>"g0ruby"</ID>
		<Answer>Woodsworth</Answer>
		<Answer>4</Answer>
		<Answer>csc309; csc343; csc318</Answer>
		<Answer>human genome; image processing</Answer>
		<Answer>Mondays, 3pm: yes</Answer>
		<Answer>Mondays, 4pm: yes</Answer>
		<Answer>Tuesday evenings (after 5pm): no</Answer>
		<Answer>Fridays, 11am: no</Answer>
	</Student>
	<Student>
		<ID>"g0arthur"</ID>
		<Answer>UC</Answer>
		<Answer>3</Answer>
		<Answer>csc336/350; csc318</Answer>
		<Answer>location-aware apps; human genome</Answer>
		<Answer>Mondays, 3pm: yes</Answer>
		<Answer>Mondays, 4pm: yes</Answer>
		<Answer>Tuesday evenings (after 5pm): yes</Answer>
		<Answer>Fridays, 11am: no</Answer>
	</Student>
	<Student>
		<ID>"g0dw"</ID>
		<Answer>Trinity</Answer>
		<Answer>2</Answer>
		<Answer>csc309; csc343</Answer>
		<Answer>human genome; location-aware apps</Answer>
		<Answer>Mondays, 3pm: no</Answer>
		<Answer>Mondays, 4pm: yes</Answer>
		<Answer>Tuesday evenings (after 5pm): yes</Answer>
		<Answer>Fridays, 11am: no</Answer>
	</Student>
	<Student>
		<ID>"g0franci"</ID>
		<Answer>college not given</Answer>
		<Answer>3</Answer>
		<Answer>csc343</Answer>
		<Answer>human genome; encryption</Answer>
		<Answer>Mondays, 3pm: no</Answer>
		<Answer>Mondays, 4pm: yes</Answer>
		<Answer>Tuesday evenings (after 5pm): no</Answer>
		<Answer>Fridays, 11am: no</Answer>
	</Student>
	<Student>
		<ID>"g0brain"</ID>
		<Answer>did not submit survey</Answer>
	</Student>
</Responses>
